name: Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged

    steps:
      - name: Compute next SemVer tag
        id: semver
        uses: cloud-crafts/semver-release-action@master
        with:
          release_branch: master
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.base_ref }}

      - run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u kphoen --password-stdin

      - name: Push docker image
        run: make push
        env:
          VERSION: ${{ steps.semver.outputs.tag }}

      - run: make update_action
        env:
          VERSION: ${{ steps.semver.outputs.tag }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release ${{ steps.semver.outputs.tag }}
          branch: master

      - name: Create release
        id: tag
        uses: cloud-crafts/semver-release-action@master
        with:
          release_branch: master
          tag: ${{ steps.semver.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
